import type { Metadata } from "next";
import Link from "next/link";
import LegalShell from "../legal-shell";

export const metadata: Metadata = { title: "Privacy Policy — Qpy Engage" };

export default function PrivacyPage() {
  return <LegalShell>
    <p className="legal-eyebrow">Legal</p>
    <h1>Privacy Policy</h1>
    <p className="legal-updated">Effective August 1, 2026</p>

    <section><h2>1. About this policy</h2><p>Qpy Engage provides tools for businesses to manage customer conversations, messaging channels, campaigns, automations, and AI assistants. This policy explains how Qpy Engage processes information when you use the service or connect a Meta, WhatsApp Business, Instagram, or web-chat account.</p></section>
    <section><h2>2. Information we process</h2><ul><li>Account and workspace information, including names, contact details, roles, and preferences.</li><li>Channel connection details supplied through authorized platform sign-in flows, such as business account, phone-number, page, and channel identifiers.</li><li>Customer conversations, message status events, contact records, campaign audiences, templates, uploaded training sources, and automation settings that you choose to manage through Qpy Engage.</li><li>Technical and usage information needed to operate, secure, diagnose, and improve the service.</li></ul></section>
    <section><h2>3. How information is used</h2><p>We use information to provide requested messaging and automation features, deliver and organize conversations, train and operate assistants according to workspace instructions, provide analytics, secure accounts, troubleshoot problems, comply with law, and communicate about the service.</p></section>
    <section><h2>4. Automated processing and artificial intelligence</h2><p>Qpy Engage uses AI to draft assistant replies, summarize a conversation when it is handed to a human agent, suggest daily follow-ups, and produce a lead score. To do this, the relevant conversation content is sent to Anthropic’s Claude API for processing and a result is returned. Anthropic acts as a processor for Qpy Engage and does not use this content to train its models.</p><p>The lead score is an automated rating of how likely a conversation is to lead to business. It is a guide for your team, is always visible alongside the reasons given for it, and is never used to make a decision about a person without a human involved.</p></section>
    <section><h2>5. Linking identities across channels</h2><p>So that a customer who reaches you on more than one channel is not treated as several different people, Qpy Engage matches records using normalized identifiers — a phone number reduced to a standard international format, a lowercased email address, or an Instagram handle. Where these match, the conversations are shown together as one customer profile.</p><p>Profiles can be merged by your team. A merged profile is retained as a reference to the surviving record rather than erased, so that historical links keep working. Nothing is matched across different workspaces or different customers of Qpy Engage.</p></section>
    <section><h2>6. Meta and messaging platforms</h2><p>When you connect a supported channel, Qpy Engage processes information under the permissions you approve. Platform data is used only to provide the connected features and is also subject to the applicable platform’s terms and policies. Qpy Engage does not sell platform data.</p></section>
    <section><h2>7. Sharing</h2><p>Information may be shared with service providers that help host, secure, monitor, or deliver Qpy Engage; with connected messaging platforms as required to perform your instructions; during a business reorganization; or when required by law. Providers are permitted to process information only for the services they supply.</p><p>The providers that process customer content on our behalf are Cloudflare (hosting, storage, and network), Anthropic (AI processing as described above), and Meta Platforms (delivery of WhatsApp and Instagram messages). Where a workspace administrator connects HubSpot or Salesforce and chooses to send a contact to it, that contact’s details are transferred to that provider and are then governed by its own privacy policy.</p></section>
    <section><h2>8. Retention and security</h2><p>Information is retained for as long as needed to provide the service, meet contractual or legal requirements, resolve disputes, and maintain security. Access tokens for connected channels are encrypted before storage. We use reasonable administrative and technical safeguards, but no internet service can guarantee absolute security.</p></section>
    <section><h2>9. Marketing messages and consent</h2><p>Broadcast messages are only sent to a customer on a channel where there is a record of consent for that channel — either an explicit opt-in, or the customer having messaged the business first on it. Consent is recorded per channel, so a customer may be reachable on one and not another. An explicit opt-out always takes precedence and is not overridden by later activity.</p></section>
    <section><h2>10. Your choices</h2><p>Workspace administrators can disconnect channels, update connected data, record or withdraw consent for any identifier, and request access, correction, export, or deletion. You may also remove Qpy Engage from the integrations or business settings of the connected platform. Deletion requests are described on the <Link href="/data-deletion/">Data deletion</Link> page.</p></section>
    <section><h2>11. International processing and children</h2><p>Information may be processed in countries where Qpy Engage or its service providers operate, subject to applicable safeguards. Qpy Engage is a business service and is not directed to children.</p></section>
    <section><h2>12. Updates</h2><p>We may update this policy as the service or legal requirements change. The effective date above identifies the latest version.</p></section>
    <section className="legal-callout"><h2>Contact</h2><p>For privacy questions or requests, email <a href="mailto:praveen.madipoju3@gmail.com">praveen.madipoju3@gmail.com</a>.</p></section>
  </LegalShell>;
}
